#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ARLAP96070PET
#PBS -q gpu
#PBS -l select=1:ncpus=10:accelerator_model=Tesla_K40s
#PBS -l walltime=168:00:00
#PBS -j oe
#PBS -V 

cd $wdmersenne/gpu/002/

aprun ./cpu_calibrate -d > timing_results.out

