#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ARLAP96070PET
#PBS -q standard
#PBS -l select=16:ncpus=8:mpiprocs=8
#PBS -l walltime=24:00:00
# The value of ncpus refers to the number of physical cores available on each node. Standard compute nodes on Topaz will require ncpus=36.

# queue: # debug standard background

export gflags=gflags_predator
export myProject=${myGit}'fortran/tools/test/stress/d_shared'
echo $myProject
cd ${myProject}
module switch intel-compilers/12.1.0 gcc-compilers/4.7.3
make
rm -f *.o *.temp *.mod *.smod

## Execution Block ----------------------------------------------
# Environment Setup
# cd to your scratch directory in /work
cd ${WORKDIR}

# create a job-specific subdirectory based on JOBID and cd to it
JOBID=`echo ${PBS_JOBID} | cut -d '.' -f 1`
if [ ! -d ${JOBID} ]; then
  mkdir -p ${JOBID}
fi
cd ${JOBID}

## Launching -----------------------------------------------------
# copy executable from $HOME and submit it
cp -a ${myProject}/. .

${fortran_execute_mpi} -n 128 ./cpu > out.dat

## Clean up -----------------------------------------------------
# Remove temporary files
rm -f *.o *.temp *.mod *.smod
