#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ERDCS97270PET
#PBS -q standard
#PBS -l select=8:ncpus=16:mpiprocs=16
#PBS -l walltime=10:00:10
#PBS -j oe
#PBS -V

# Both the number of nodes and processes per node are specified using the same directive as follows, where N1 is the number of nodes you are requesting and N2 is the number of processes per node (must be 1, 2, 4, 8, or 16):

#PBS -l select=N1:ncpus=16:mpiprocs=N2

# The value of ncpus refers to the number of physical cores available on each node, and must always be set to 16. An exception to this rule is the transfer queue, which uses the directive below:

# PBS -l select=1:ncpus=1

# queue: # debug standard background

export myProject=${myGit}'fortran/tools/test/stress/d_shared'
echo $myProject
cd ${myProject}
module switch intel-compilers/12.1.0 gcc-compilers/4.8.4
make
rm -rf *.o *.mod *.smod *.dSYM

## Execution Block ----------------------------------------------
# Environment Setup
# cd to your scratch directory in /work
cd ${WORKDIR}

# create a job-specific subdirectory based on JOBID and cd to it
JOBID=`echo ${PBS_JOBID} | cut -d '.' -f 1`
if [ ! -d ${JOBID} ]; then
  mkdir -p ${JOBID}
fi
cd ${JOBID}

## Launching -----------------------------------------------------
# copy executable from $HOME and submit it
cp -a ${myProject}/. .

${fortran_execute_mpi} -n 128 ./cpu > out.dat

## Clean up -----------------------------------------------------
# Remove temporary files
rm -rf *.o *.mod *.smod *.dSYM

