#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -V
#PBS -A ERDCS97270PET
#PBS -q standard
#PBS -l select=1:ncpus=36:mpiprocs=36:vnode=r24i1n5
#PBS -l walltime=4:00:00
#PBS -j oe

export myProject=${fortran}'tools/test/stress/flopper/delta/echo_thunder'
echo $myProject
cd ${myProject}

#module switch intel-compilers/15.0.3 gcc-compilers/5.3.0
module switch compiler/intel/15.0.3 compiler/gcc/5.3.0
make
rm -rf *.o *.mod *.smod *.dSYM

## Execution Block ----------------------------------------------
# Environment Setup
# cd to your scratch directory in /work
cd ${WORKDIR}

# create a job-specific subdirectory based on JOBID and cd to it
JOBID=`echo ${PBS_JOBID} | cut -d '.' -f 1`
if [ ! -d ${JOBID} ]; then
  mkdir -p ${JOBID}
fi
cd ${JOBID}

qstat -f ${PBS_JOBID} | grep ${BC_HOST}_

## Launching -----------------------------------------------------
# copy executable from $HOME and submit it
cp -a ${myProject}/.  .

${fortran_execute_mpi}  ./flops > out.dat

## Clean up -----------------------------------------------------
# Remove temporary files
rm -rf *.o *.mod *.smod *.dSYM

