#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -V
#PBS -A ARLAP96070PET
#PBS -q debug
#PBS -l select=1:ncpus=36:mpiprocs=36
#PBS -l walltime=1:00:00
#PBS -j oe

source ${myGit}bash/pbs_pulse

cd ${PBS_0_WORKDIR}
export gflags=${gflags_topaz}
module switch intel-compilers/ gcc-compilers/6.1.0
make
rm -rf *.o *.mod *.smod *.dSYM

## Execution Block ----------------------------------------------
# Environment Setup
# cd to your scratch directory in /work
cd ${WORKDIR}

# create a job-specific subdirectory based on JOBID and cd to it
JOBID=`echo ${PBS_JOBID} | cut -d '.' -f 1`
if [ ! -d ${JOBID} ]; then
  mkdir -p ${JOBID}
fi
cd ${JOBID}

## Launching -----------------------------------------------------
# copy executable from $HOME and submit it
cp -a ${PBS_0_WORKDIR}/.  .

${fortran_execute_mpi}  ./flops > out.dat

## Clean up -----------------------------------------------------
# Remove temporary files
rm -rf *.o *.mod *.smod *.dSYM

