#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ERDCS97290KAT
#PBS -q standard
#PBS -l select=1:ncpus=10:mpiprocs=10
#PBS -l walltime=168:00:00
#PBS -j oe
#PBS -N direct
#PBS -V 

cd $wdmersenne/cpu/003/

./cpu_measure -d > timing_results.out

