#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ARLAP96070PET
#PBS -q gpu
#PBS -l select=1:ncpus=10:accelerator_model=Tesla_K40s
#PBS -l walltime=120:00:00
#PBS -j oe
#PBS -N direct
#PBS -V 

cd $wdmersenne/gpu/003/

./cpu -d > timing_results.out

