#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ARLAP96070PET
#PBS -q GPU
#PBS -l select=1:ncpus=28:mpiprocs=28:ngpus=1
#PBS -l walltime=120:00:00
#PBS -j oe
#PBS -N direct
#PBS -V 

cd $wdmersenne/GPU/001/

./cpu -d > timing_results.out

