#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ERDCS97270PET
#PBS -q standard
#PBS -l select=2:ncpus=36:mpiprocs=36
#PBS -l walltime=24:00:00
#PBS -j oe
#PBS -V

# PBS -l select=N1:ncpus=36:mpiprocs=N2
# The value of ncpus refers to the number of physical cores available on each node. Standard compute nodes on Topaz will require ncpus=36.

# An exception to this rule is the transfer queue, which uses the directive below:
# PBS -l select=1:ncpus=1

# queue: # debug standard background

export myProject='/p/home/dantopa/hpc/fortran/tools/test/stress/topaz'
echo $myProject
cd ${myProject}
module switch compiler/intel compiler/gcc/5.3.0
make
rm -rf *.o *.mod *.smod *.dSYM

## Execution Block ----------------------------------------------
# Environment Setup
# cd to your scratch directory in /work
cd ${WORKDIR}

# create a job-specific subdirectory based on JOBID and cd to it
JOBID=`echo ${PBS_JOBID} | cut -d '.' -f 1`
if [ ! -d ${JOBID} ]; then
  mkdir -p ${JOBID}
fi
cd ${JOBID}

## Launching -----------------------------------------------------
# copy executable from $HOME and submit it
cp -a ${myProject}/. .

# CRAY MPICH parallel code built with the CRAY compiler.
# mpiexec_mpt command for CRAY MPICH2 codes and ccmrun for any serial, shared-memory, or non-native MPI codes
mpiexec_mpt -n 72 ./cpu topaz > out.dat

## Clean up -----------------------------------------------------
# Remove temporary files
rm -rf *.o *.mod *.smod *.dSYM

# http://www.erdc.hpc.mil/docs/topazPbsGuide.html
# submit it to PBS for execution e.g. "qsub run.pbs"
