#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ARLAP96070PET
#PBS -q standard
#PBS -l select=1:ncpus=28:mpiprocs=28:ngpus=1
#PBS -l walltime=168:00:00
#PBS -j oe
#PBS -V 

cd $wdmersenne/gpu/004/

mpiexec_mpt ./cpu_calibrate -d > timing_results.out

