#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ARLAP96070PET
#PBS -q bigmem
#PBS -l select=1:ncpus=36:mpiprocs=36:bigmem=1
#PBS -l walltime=120:00:00
#PBS -j oe
#PBS -N direct
#PBS -V 

cd $wdmersenne/bigmem/003/

./cpu -d > timing_results.out

